=for comment
podchecker pdftest.pod && pod2html --infile=pdftest.pod --outfile=pdftest.html
open pdftest.html and click 'reload'
also
conversion for PDF reading is:
pod2pdf pdftest.pod --icon-scale 0.25 --title "PDL Book" --icon logo2.png --output-file pdftest.pdf

=head1 Testing HTML and PDF Creation with pod2html and pod2pdf

One-line summary:

Make an 8-bit color PNG with width 800 pixels and add this line in the
POD:

    =for html  <img WIDTH=400 src="path_to_image/image.png">

Longer explanation:

Images for HTML and PDF generation should come from the single PNG image
with 8 bit color and a width of 800 pixels.  The PNG should be C<8
bit-color> as reported by running the C<file image.png> command in unix.
The height can be unconstrained.

Only the HTML code should be added in a POD document - I have a script
that will automatically add the correct pod formatting code for a PDF image
afterwards. This is done because C<podchecker> complains about the pod
formatting code for the PDF image.

=head2 (IGNORE) Sandbox for testing pod2html and pod2pdf

Here are the images ex_env1.png and ex_env1.8.png:

=for html <img src="PGPLOTFigs/ex_env1.png">

Now I'm trying the WIDTH parameter in the HTML code so that if this
works, we can use the 800 pixel image and scale it down for this
HTML.

Here's the unscaled version:

=for html <img src="PGPLOTFigs/ex_env1.8.png">

Here's a version scaled to width=400:

=for html <img WIDTH=400 src="PGPLOTFigs/ex_env1.8.png">

Excellent! This works for Safari, Chrome and Firefox. I'll keep this in
then.

=for O<PGPLOTFigs/ex_env1.8.png>

=for comment convert ex_env1.pdf -rotate 90 -resize 300x ex_env2.png

This should have one size picture in HTML and another in the PDF
document.

Now trying logo2.png in the current directory for the PDF:

O<logo2.png>

It should be above this line.

The problem is that the O < tag is marked as an error in podchecker.
There's no solution for this at the moment.

O<PGPLOTFigs/ex_env1.8.png>
